### ISSUE TITLE
Different board revision 

### ISSUE THREAD

**Issue by hboyd2003** [mill1000/esphome-winix-c545#11]
Hello, I looks like I have a different board revision than what is in the tutorial (although they are both v1). Below are some images of the board and info.
I was able to trace the RX and TX to a empty through hole (labeled MCU_TP) which I soldered screw terminals to. Unfortunately, I was unable to figure out how to pull the RST pin for the wifi down. The rst pin now heads into an unlabeled chip. Luckily the code works on this board revision and I had no trouble with anything else.

Board:
- Revision: 1.0
- Name: C545 PBA DISPLAY_WFM50
- Production date: 2021

 MCU: 
- Manufactuer: ABOV
- Model: A31G123RLN
- [Product Page](https://www.abov.co.kr/en/products/product_device.php?category=32bit_mcu_g1_series&device=A31G123RN)

WiFi:
- Manufactuer I&C Technonolgy 
- Model: WFM50-SFC201
- [Product Page](http://www.inctech.co.kr/kr/product/product_view.php?idx=20)
 
 <details>
  <summary>Front Images</summary>
  
![IMG_0139](https://github.com/mill1000/esphome-winix-c545/assets/8950185/e3e22a44-88f2-4e22-9f5f-afb3f6331050)
![IMG_0124](https://github.com/mill1000/esphome-winix-c545/assets/8950185/e9223889-993e-44ac-b9e7-bca4715d9def)
![IMG_0125](https://github.com/mill1000/esphome-winix-c545/assets/8950185/a010fb58-19ff-4cd4-9b4f-e797fc616910)
![IMG_0127](https://github.com/mill1000/esphome-winix-c545/assets/8950185/97bde74d-ad49-44ce-8347-cd560500fd3f)

  
</details>

 <details>
  <summary>Back Images</summary>
  
![IMG_0128](https://github.com/mill1000/esphome-winix-c545/assets/8950185/909b574d-0f00-4b24-a0f2-528a189b5d16)
![IMG_0129](https://github.com/mill1000/esphome-winix-c545/assets/8950185/2c0f50f6-4d9f-4a7b-b632-fa8156827e44)
![IMG_0130](https://github.com/mill1000/esphome-winix-c545/assets/8950185/65f894e3-49a9-4116-927e-0a4d5a8e18b2)
![IMG_0131](https://github.com/mill1000/esphome-winix-c545/assets/8950185/a9b863ab-6a8b-4ab2-a8d8-57cdb0b13ef0)

  
</details>

**Comment by YoungsterJon** [comment]
RST pin to WiFi module is Q12. One of my machines is the same model as this.

![wfm50_rst_pin](https://github.com/mill1000/esphome-winix-c545/assets/69780894/c86cae74-7a54-4dc3-94e2-00da76816162)

**Comment by mill1000** [comment]
Looks like the RST might even be broken out on that MCU_TP header. Lucky you!

Thanks for this information. I might create a project wiki to contain some of this information.

**Comment by mill1000** [comment]
Added a [wiki](https://github.com/mill1000/esphome-winix-c545/wiki/Alternate-Board-Design) page with this information. Thanks for the contribution.
