### ISSUE TITLE
ESP32-PICO-KIT V4.1 Board Availability

### ISSUE THREAD

**Issue by marshalltech81** [mill1000/esphome-winix-c545#14]
Thank you for your project as this solves a problem I have with the Winix C545 machines.  

I hate to ask but I am new to the ESPHome ecosystem and when I currently look up the ESP32-PICO-KIT V4.1 boards for sale most places do not appear to have them in stock.  Is there a follow up board you would recommend in its stead? I do see places having the ESP32-PICO-V3 available.

Thank you in advance!

**Comment by mill1000** [comment]
Hi.

I think a ESP32-PICO-V3 would be just fine. A ESP32-DevKitC or a Pi Pico W should work too. This project doesn't have any specific HW requirements beyond having enough IO exposed for the UART.

**Comment by marshalltech81** [comment]
Thank you!
