### ISSUE TITLE
Feature Request: Control of LEDs?

### ISSUE THREAD

**Issue by elykrk** [mill1000/esphome-winix-c545#4]
Hi, thanks for putting this together. I haven't opened up the C545 yet but is there any possibility for control over the leds as well? Would love to be able to disable the "sleep" mode light entirely or after a few seconds/minute after this mode is enabled.

**Comment by mill1000** [comment]
Hi

Unfortunately no, I don't think you can control the individual LEDs via the UART protocol.

You could however locate the FETs controlling the LEDs and wire them up to some GPIOs. There'd be drive fights with the device MCU but it might be feasible.

**Comment by elykrk** [comment]
Got it thank you!
