### ISSUE TITLE
Code Crashes Pico W

### ISSUE THREAD

**Issue by ad3m3r5** [mill1000/esphome-winix-c545#7]
Thanks to some back and forth info exchange with @mill1000, I was able to narrow it down to an issue with `sscanf` and `%3d` for `uint16_t api_code`.

The issue appears to be completely fixed (#6 ), but might need to be tested on an ESP32 just to make sure it doesn't cause issues there.

**Comment by mill1000** [comment]
Thanks for finding this latest bug. Looks like I was string to sscanf a 32-bit int into a 16-bit variable. Closed with #6
